### PR TITLE
Added setprefix using database

### PR DESCRIPTION
**Pull request by LejhandGamingYT**

### CODE REVIEW

**Review by j-dogcoder — CHANGES_REQUESTED** [review]
PR should be into staged branch

**Review by j-dogcoder — APPROVED** [review]

**Comment by j-dogcoder** [comment]
Looks good @LejhandGamingYT! Wait for those statuses to finish up and then you are all set to merge

**Comment by LejhandGamingYT** [comment]
> Looks good @LejhandGamingYT! Wait for those statuses to finish up and then you are all set to merge

👍👍

**Comment by j-dogcoder** [comment]
> > Looks good @LejhandGamingYT! Wait for those statuses to finish up and then you are all set to merge
> 
> 👍👍

If they don’t finish soon I will speed a few things along.

**Pull request merged**
