### PR TITLE
Remove node_modules folder and Updates gitignore file

### PR DESCRIPTION
**Pull request by thinkverse**
This PR removes the `node_modules`folder from the repository and updates the `.gitignore` to the "default" node gitignore found in the [github/gitignore](https://github.com/github/gitignore) repository. 🙂

### CODE REVIEW

**Review by j-dogcoder — APPROVED** [review]
Thanks for your contribution @thinkverse. In the future, we want to merge into the Staged branch.

**Comment by thinkverse** [comment]
> Thanks for your contribution @thinkverse. In the future, we want to merge into the Staged branch.

My bad. Didn't read the documentation correctly, sorry. 👏

**Comment by j-dogcoder** [comment]
Small issue @thinkverse. I pulled down the changes and it removed all that. They are still needed on my Machine. Any solution for getting them back?

**Comment by thinkverse** [comment]
> Small issue @thinkverse. I pulled down the changes and it removed all that. They are still needed on my Machine. Any solution for getting them back?

`npm install` will install the dependencies like normal, that's why it's unnecessary for git to track vendor folders, cuz installing it will pull down the dependencies locally anyway.

**Comment by j-dogcoder** [comment]
Thanks. I believe there may need to be a slight change to the install directions in the readme as well.

**Comment by thinkverse** [comment]
I'll push an updated `README.md` in a few, need to grab something to eat first. 🙂

**Comment by j-dogcoder** [comment]
Thanks!

**Comment by j-dogcoder** [comment]
@thinkverse Something that would be super useful to work on is Issue #3. It is a mammoth task but even if someone just gets started that would be amazing.

**Pull request merged**
