### PR TITLE
Fixed Avatar Command

### PR DESCRIPTION
**Pull request by BennovanDorst**
Fixed avatar command as MessageEmbed() wasn't defined

### CODE REVIEW

**Review by j-dogcoder — COMMENTED** [review]
This looks good @BennovanDorst! Thanks for the contribution. Please remember to check out our [contribution guide](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md). You can also join our community discord, and get a special role for being a contributor.

**Comment by BennovanDorst** [comment]
Not a problem! Just joined the Discord (Tag is: Ashlyn#0001) Looking forward to contribute even more on this project ;)

**Comment by j-dogcoder** [comment]
Put in a few tweaks that didn’t warrant sending it back to you. Merging this shortly.

**Comment by j-dogcoder** [comment]
The only thing @BennovanDorst, is that PR's should be into staged instead of master.

**Comment by BennovanDorst** [comment]
Gotcha :+1:

**Review by j-dogcoder — APPROVED** [review]

**Pull request merged**
