### PR TITLE
Removed unnecessary args and fixed Hug and Slap command

### PR DESCRIPTION
**Pull request by squarecylinder**
This is for the issue #150, It seems like the original implementation of these two commands were copy-pasta but weren't configured properly. The arg that is being passed in is message which isn't really the message object for some reason, so I had to add .message to message to get the object. Once I added that everything worked except Discord.MessageEmbed() was undefinied. I deleted the arg that was being passed Discord and used const Discord = require('discord.js') this fixed the issue completely. Took everything I found out from hugs and put it in slap. You should be good to go! 
image
I deleted my uses of some of the commands to fit everything in a screen shot!

### CODE REVIEW

**Comment by j-dogcoder** [comment]
Hey @squarecylinder Make sure to check out [Contributing.md](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md)!

**Comment by squarecylinder** [comment]
> Hey @squarecylinder Make sure to check out [Contributing.md](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md)!

Just realized I made the PR for master and not staging, my bad! Do I need to remake the request or can I just change the branch?

**Review by j-dogcoder — CHANGES_REQUESTED** [review]
Hey @squarecylinder! Let's leave the example-config.json in please

**Comment by j-dogcoder** [comment]
> > Hey @squarecylinder Make sure to check out [Contributing.md](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md)!
> 
> Just realized I made the PR for master and not staging, my bad! Do I need to remake the request or can I just change the branch?

I fixed it.

**Review by j-dogcoder — APPROVED** [review]

**Pull request merged**
