### PR TITLE
Lock and Unlock commands on specific role only

### PR DESCRIPTION
**Pull request by Uklizdev**
I made it so the commands need the ID of the role you want to lock or unlock the channel for and it updates the permissions only for that specific role. Lots of changes appear because Prettier autoformated my code.

### CODE REVIEW

**Review by j-dogcoder — COMMENTED** [review]
Will this work if someone @ mentions a role as an arg instead of an id? Can it be both?

**Comment by j-dogcoder** [comment]
PR Closes #187

**Review by j-dogcoder — CHANGES_REQUESTED** [review]
Will this work if someone @ mentions a role as an arg instead of an id? Can it be both?

**Comment by j-dogcoder** [comment]
Testing now @Uklizdev!

**Comment by Uklizdev** [comment]
Made a new pull request, now it allows mentions or IDs

**Pull request closed without merging**
