### PR TITLE
Translated messages.json into Arabic (AR)

### PR DESCRIPTION
**Pull request by MidouWebDev**
The bot supports now the arabic language !

### CODE REVIEW

**Comment by j-dogcoder** [comment]
@MidouWebDev Did you mean to close this?

**Comment by MidouWebDev** [comment]
@j-dogcoder i forgot to create a branch so now i am in the patch-1 and i will commit now the full translation so i am going to be reopening it in a few minutes to commit my work.

**Comment by MidouWebDev** [comment]
@j-dogcoder Here is my PR related to the messages translation into arabic. Need your Review

**Review by j-dogcoder — APPROVED** [review]

**Review by j-dogcoder — APPROVED** [review]
@MidouWebDev FYI, PRs in that repo should be into staged not master.

**Pull request merged**
