### PR TITLE
Translated the messages.json to French (FR)

### PR DESCRIPTION
**Pull request by MidouWebDev**
The bot can support now the french language !

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@j-dogcoder here is my PR related to the messages translation to french !

**Comment by MidouWebDev** [comment]
@j-dogcoder i see that i can't ask for your review. I don't know why !

**Comment by j-dogcoder** [comment]
Super weird! I am taking a look now.

**Review by j-dogcoder — DISMISSED** [review]
Made some minor fixes! Good to go now!

**Review by j-dogcoder — APPROVED** [review]
Approved with correct branch.

**Pull request merged**
